### ISSUE TITLE
Caixa de texto para fazer commit na plataforma

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#10]
A caixa de texto para registrar o log do commit está muito pequena. Deste tamanho as pessoas vão achar que precisam escrever apenas uma palavra ali dentro.

**Comment by gutosurrex** [comment]
Feito

**Comment by simas0** [comment]
Pode colocar com três linhas? Digo, para que  o usuário tenha certeza de que pode escrever sem dó.

**Comment by gutosurrex** [comment]
Cara, o git tem dois espaco para escrever nos commits: um para a mensagem (tipo "Rorrige erros de portugues na atividade triangulo"). Depois tem um lugar para escrever um texto grande.

Se eu entendi bem, eu devo implementar essa janela de texto grande, certo?
--

**Comment by gutosurrex** [comment]
Cara, o git tem dois espaco para escrever nos commits: um para a mensagem (tipo "Rorrige erros de portugues na atividade triangulo"). Depois tem um lugar para escrever um texto grande.

Se eu entendi bem, eu devo implementar essa janela de texto grande, certo?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

On October 4, 2016 7:45:09 AM GMT-03:00, Fabio Simas <notifications@github.com> wrote:
>Pode colocar com três linhas? Digo, para que  o usuário tenha certeza
>de que pode escrever sem dó.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/gutosurrex/BookCloud/issues/10#issuecomment-251355213

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by simas0** [comment]
sim

Em 04/10/2016 17:09, "gutosurrex" <notifications@github.com> escreveu:

> Cara, o git tem dois espaco para escrever nos commits: um para a mensagem
> (tipo "Rorrige erros de portugues na atividade triangulo"). Depois tem um
> lugar para escrever um texto grande.
>
> Se eu entendi bem, eu devo implementar essa janela de texto grande, certo?
> --
> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>
> On October 4, 2016 7:45:09 AM GMT-03:00, Fabio Simas <
