### ISSUE TITLE
Nomes válidos para nome de ramo levam a "Internal serve error"

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#11]
Primeiro: no momento de inserção do nome do novo ramo deviam estar escritas as restrições para o nome.

Segundo: se ainda assim o usuário escrever um nome inválido para o ramo, então deveria surgir NA MESMA TELA uma mensagem informando QUAL o erro aconteceu e não apenas uma mensagem genérica de erro.

**Comment by gutosurrex** [comment]
Corrigidos!
