### ISSUE TITLE
Barra de navegação permanente na plataforma

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#13]
As opções abaixo deveriam estar disponíveis a todo momento na plataforma desde o início, inclusive nos momentos de edição e não apenas dentro de algum ramo. 

Como alguém vai colocar uma dúvida de inserção de texto nos ISSUES? Hoje ela teria que sair do ambiente de edição. Além disso, todos estes links devem abrir em nova aba.

    Página do projeto
    Discussões do livro
    Discussões da plataforma
    Staff only

**Comment by gutosurrex** [comment]
Eu pensei que essa barra permanente deveria ficar no sidebar. Nesse caso, ela poderia ficar acessível em todos os momentos, exceto no edit, review e diff (pois esses já tem duas colunas e ficaria apertado). O que você acha?

Algo que pode ser útil para abrir em outra aba:

http://stackoverflow.com/a/11718325

**Comment by simas0** [comment]
Nestas duas páginas (edit e diff) os 4 links poderiam entrar na barra azul que fica no topo da página. Em edit está escrito agora apenas o nome do ramo.

**Comment by gutosurrex** [comment]
Coloquei os principais na barra azul. Quatro seria demais.

**Comment by simas0** [comment]
Excelente trabalho!
É possível colocá-los no meio da linha para evitar confundir com a
navegação do projeto?

Fábio
(21) 99735-8504

2016-10-09 19:02 GMT-03:00 gutosurrex <notifications@github.com>:
