### ISSUE TITLE
Botão de commit devia aparecer no momento da edição.

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#15]
Senão vai ser um show de gente achando que enviou, mas não enviou.

**Comment by gutosurrex** [comment]
Agora tem uma mensagem vermelha de uncommitted changes. Isso basta por hora?

**Comment by simas0** [comment]
Vamos ver se basta. O Marcos Paulo parece não ter entendido que é
necessário clicar em commit para enviar as alterações. O ideal é que essas
coisas sejam intuitivas a partir da visualização da plataforma.

Em 02/10/2016 23:18, "gutosurrex" <notifications@github.com> escreveu:

**Comment by simas0** [comment]
Parece bom o suficiente para mim. Vou fechar e reabrimos se for necessário.
