### ISSUE TITLE
Na página de edição deve aparecer o ramo que está sendo editado

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#17]
O usuário deve poder conferir o ramo que está editando. De preferência aparecer também de quem é o ramo.

**Comment by simas0** [comment]
Coloquei a prioridade alta porque isso confunde o usuário.

**Comment by gutosurrex** [comment]
Está na barra de endereços, isso não basta?

**Comment by simas0** [comment]
Acho melhor incluir na janela também. Eu nem vi isso lá.

**Comment by gutosurrex** [comment]
Feito
