### ISSUE TITLE
As tags "clone" e "requests" não deveriam aparecer juntas..

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#19]
Contudo olhe a imagem abaixo. Coloquei a prioridade alta porque isso confunde o usuário.

![screenshot from 2016-10-02 14-29-46](https://cloud.githubusercontent.com/assets/16407253/19022355/e1f77f2a-88ac-11e6-9b81-3efdc9d4eb32.png)

**Comment by simas0** [comment]
Pior: eu posso clicar em requests, ver as mudanças, mas não posso aceitá-las. Diz que não sou o proprietário do ramo. O objetivo é que quem está visualizando possa saber que outro já sugeriu modificações? Pode fazer sentido então. Mas me parece confuso.

**Comment by gutosurrex** [comment]
Resolvido!
