### ISSUE TITLE
Quero ser colaborador deste repositório para criar novos recursos.

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#2]

**Comment by gutosurrex** [comment]
Eu estou adicionando um label chamado `external collaborators` para issues que eu acho que podem receber ajuda externa sem muitas tecnicalidades. Já tem uma feita especialmente pra você, hehe...

Se você for ajudar, faca um fork e um pull request. Dá pra fazer isso tudo no próprio Github.

**Comment by simas0** [comment]
Algumas alterações, como criar label, não podem ser feitas por fork.

Fábio
(21) 99735-8504

2016-09-28 11:12 GMT-03:00 gutosurrex <notifications@github.com>:

**Comment by gutosurrex** [comment]
Te mandei um convite
