### ISSUE TITLE
Estrutura de arquivos dentro de "ensino_medio"

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#20]
Pelo que entendi precisamos ter um projeto único para possibilitar as referências entre livros e a geração de um arquivo único. 

Minha sugestão é que o projeto seja ensino_médio com os seguintes arquivos permanentes abaixo. Os demais arquivos devem surgir como ramos dos arquivos geometria, grandezas e medidas, etc. e desaparecem quando são aprovados, mas retornam com uma mensagem de rejeição do revisor quando rejeitados.

ensino médio: (by simas)
 *  volume 1 (by simas)

      **   geometria (by marcos)

      **   grandezas e medidas (by marcos)

      **   probabilidade e estatística (by luciane)

      **   números e operações (by gladson)

    **   álgebra e funções (by gladson)

 *  volume 2 (by simas)

    **   geometria (by marcos)

    **   grandezas e medidas (by marcos)

    **   probabilidade e estatística (by luciane)

    **   números e operações (by gladson)

    **   álgebra e funções (by gladson)

 *  volume 3 (by simas)

     **   geometria (by marcos)

     **   grandezas e medidas (by marcos)

     **   probabilidade e estatística (by luciane)

     **   números e operações (by gladson)

     **   álgebra e funções (by gladson)

**Comment by simas0** [comment]
Talvez o ideal seja ter um arquivo para cada volume da coleção porque não esperamos ter um html ou pdf com a coleção inteira. Neste caso fica a pergunta se poderemos fazer referência a atividades que estejam em outro volume da coleção.

**Comment by gutosurrex** [comment]
Decisao importante essa. Se separamos ou nao cada volume em um projeto.
--
