### ISSUE TITLE
Possibilitar a separação do livro do professor do livro do estudante no html e no pdf

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#22]
Vamos começar a escrever esta semana: como devemos inserir os comentários para o professor? como devemos inserir as respostas das atividades?

**Comment by gutosurrex** [comment]
Eu acho que uma boa possibilidade seria pulverizar o livro em arquivos (como fizemos para o outro projeto). Se tivermos arquivos só para o professor, um para o aluno e um para respostas, isso estaria contornado. Temos que discutir isso melhor, mas sempre podemos mudar no meio do caminho.

**Comment by simas0** [comment]
Eu não gosto desta opção. Nela temos dois problemas a meu ver:
1. aumenta a complexidade de uso da plataforma pois cada vez que o elaborador for fazer uma nova atividade, terá que criar um novo arquivo e  teremos um arquivo que apenas chama vários outros arquivos.
2. torna-se um martírio fazer mudanças ao longo de todo o texto (embora isso seja possível de se fazer na versão local da pasta no github utilizando um editor de texto que faz buscar e substituições de expressões em toda a pasta).

**Comment by gutosurrex** [comment]
Estou ficando a favor de uma solução tipo "arquivão". No sphinx existem jeitos de separar material do professor. Temos que implementar, mas eu já olhei e com certeza dá.

Vou implementar o negócio de não sair do ponto de edição ao salvar, pra melhorar o manuseio do "arquivão".

**Comment by gutosurrex** [comment]
Acho que todo o volume em um só arquivo é muito extremo. Quando eu digo arquivão eu quero dizer um para cada eixo, ou talvez até um para cada capítulo.

**Comment by simas0** [comment]
Então posso mudar o nome do arquivo? Criei um que se chama Volume_1. Mas
gostaria de mudar para Geometria_1, ou coisa parecida.

Fábio
(21) 99735-8504

2016-10-04 19:25 GMT-03:00 gutosurrex <notifications@github.com>:

**Comment by gutosurrex** [comment]
Você está confundindo. Você criou um projeto chamado Volume_1, com
um único arquivo chamado index.

Na verdade o que eu recomendo é a seguinte estrutura dentro do projeto
Volume_1:

index (com um toctree de todos os outros arquivos):

http://www.sphinx-doc.org/en/stable/markup/toctree.html

e mais um arquivo para cada capítulo (do tamanho mais ou menos de uma lição
no piloto).

Vou explicar porque o arquivo tem que ter um limite de tamanho. Todas as
vezes que a pessoa edita, salva, visualiza... ela baixa ou envia o
arquivo (e talvez as imagens). Isso faz o site ficar muito mais lento.

**Comment by simas0** [comment]
Este é um bom motivo para fazermos como você está sugerindo. Estou tentando
vender a plataforma para as equipes de elaboração e gostaria de ter os
arquivos dos capítulos criados com as propriedades (autoria, sei lá)
definidas para que eles comecem a escrever nos moldes que a equipe de
geometria está fazendo.

Fábio
(21) 99735-8504

Em 5 de outubro de 2016 09:43, gutosurrex <notifications@github.com>
escreveu:

> Você está confundindo. Você criou um projeto chamado Volume_1, com
> um único arquivo chamado index.
>
> Na verdade o que eu recomendo é a seguinte estrutura dentro do projeto
> Volume_1:
>
> index (com um toctree de todos os outros arquivos):
>
> http://www.sphinx-doc.org/en/stable/markup/toctree.html
>
> e mais um arquivo para cada capítulo (do tamanho mais ou menos de uma lição
> no piloto).
>
> Vou explicar porque o arquivo tem que ter um limite de tamanho. Todas as
> vezes que a pessoa edita, salva, visualiza... ela baixa ou envia o
> arquivo (e talvez as imagens). Isso faz o site ficar muito mais lento.
>
>
>
>
>

**Comment by gutosurrex** [comment]
Por enquanto vamos usar a seguinte sintaxe para a parte do professor:

```
.. hint::

   Don't panic!
```

E para as respostas:

```
.. tip::

   Divide by zero.
```

Depois podemos pedir features novas dessas implementações (como nome, aparência diferentes, etc...). Mas do jeito que está já não é mais crítico. Estou fechando. Abra outra pra pedir features.
