### ISSUE TITLE
Merge request não mostra dono do ramo na hora da avaliação

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#24]
Na hora de decidir se será necessário conferir alteração por alteração ou se podemos aceitar todas as mudanças diretamente ter "Request from sugestoes (by augusto)" na imagem abaixo.
![screenshot from 2016-10-02 21-08-10](https://cloud.githubusercontent.com/assets/16407253/19024897/bba0f918-88e4-11e6-96ea-47740b74379a.png)

**Comment by gutosurrex** [comment]
Feito!
