### ISSUE TITLE
Os ramos devem sumir quando o commit for aceito pelo dono do master

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#25]
Não faz sentido algum ter uma lista enorme de ramos de um arquivo, todos iguais ao master... Claro que em alguns casos específicos esperamos que permaneçam, mas o default deveria ser sumir.

**Comment by gutosurrex** [comment]
E mais complicado do que isso que você sugeriu mas está funcionando:

1. Quando alguem faz commit todos os subramos que estao limpos e não tem filhos sao marcados como obsoletos e marcados para morrer em um dia.
2. Quando alguém entra em um ramo obsoleto, ele deixa de ser obsoleto.
3. Depois de um dia de obsoletude, se algum pai ou avô dele fizer um commit ele morre.
