### ISSUE TITLE
Não é possível rejeitar commits, nem parciais nem totais.

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#27]
No final da página fica escrito `Cancel | Accept`, mas se clicamos em Cancel, somos direcionados para a página "Modificações não revisadas" (a página anterior) e a única maneira de se sair sem aceitar as alterações é clicando em voltar no navegador. E na "Lista de ramos" o arquivo ou ramo segue com a indicação "has requests". Isso foi testado em "ensino_medio" "retangulo do simas".

**Comment by gutosurrex** [comment]
Feito. Na verdade, agora temos "Review file", que é bem mais completo que somente rejeitar :)

Se você quiser rejeitar, basta entrar em Review file e "Aceitar arquivo da direita!" sem passar nenhuma das mudanças.

**Comment by gutosurrex** [comment]
Favor testar essa nova feature!

**Comment by simas0** [comment]
Acabo de experimentar em sintaxe e não tive a opção de ver as alterações feitas. Pulou da página:
![screenshot from 2016-10-04 07-11-16](https://cloud.githubusercontent.com/assets/16407253/19070485/e54dba8a-8a01-11e6-9c6d-e067ddb82ff7.png)

Para a página:

![screenshot from 2016-10-04 07-11-31](https://cloud.githubusercontent.com/assets/16407253/19070494/f333a718-8a01-11e6-835c-b8a835efe708.png)

Se me permite uma observação extra neste campo,  após clicar em  "finish request", na última tela, o link
`https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index.html` passou a redirecionar para `https://www.umlivroaberto.com/BookCloud/sintaxe/master/merge/sugestoes` (tela acima) e o único link possível nesta página leva a uma mensagem de erro dessa vez. Talvez este problema apenas tenha surgido por eu ter clicado em voltar no navegador e tentar refazer o merge (queria ver se realmente não podia conferir as alterações propostas). Mas não tenho outros requests para testar novamente. Fiz alterações num ramo by augusto no projeto do ensino-medio para você poder conferir.

**Comment by gutosurrex** [comment]
Cara, acho que eu consertei esse bug. Foi por conta de um commit vazio.
