### ISSUE TITLE
Mensagem de alerta: "Some projects have no folder..."

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#29]
Aparece logo em umlivroaberto.com/BookCloud mesmo para usuários não logados.

![screenshot from 2016-10-04 07-02-40](https://cloud.githubusercontent.com/assets/16407253/19070367/48b3e744-8a01-11e6-8872-a4ba4c4b94ef.png)

**Comment by gutosurrex** [comment]
Corrigido
