### ISSUE TITLE
Criação de ambientes

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#32]
Num primeiro momento eu diria que precisamos de três ambientes. 

1.  note, que já está lá. Mas precisa ter a palavra "note" retirada da caixa quando exibida em html e em pdf.
2. um ambiente padrão tipo um teorema em latex.
3. um específico para atividades propostas. Seria mais um tipo de seção em que temos duas colunas.

**Comment by gutosurrex** [comment]
Note que quando escrevemos dentro de um ambiente, todas linhas tem que começar com três espaços (e ambientes dentro de ambientes precisam de 6 espaços e assim por diante).

Isso pode gerar confusão na equipe quando o ambiente for muito longo?

**Comment by simas0** [comment]
Pode sim gerar confusão. Por enquanto estamos usando subseção para
atividades. Mas precisaremos de um ambiente para conversa com o professor e
para resposta. seria ótimo poder mudar a cor de fundo do texto para esses
dois ambientes destinados ao professor no html.

Fábio
(21) 99735-8504

Em 4 de outubro de 2016 19:22, gutosurrex <notifications@github.com>
escreveu:

**Comment by gutosurrex** [comment]
Se a gente for usar esse espaçamento de três espaços, aumenta muito as
possibilidades. Poderíamos a princípio fazer caixas especiais,
colapsáveis e com um botão que abre todas as caixas ao mesmo tempo.

**Comment by simas0** [comment]
Isso seria muito bom no html!

Fábio
(21) 99735-8504

Em 5 de outubro de 2016 09:36, gutosurrex <notifications@github.com>
escreveu:

> Se a gente for usar esse espaçamento de três espaços, aumenta muito as
> possibilidades. Poderíamos a princípio fazer caixas especiais,
> colapsáveis e com um botão que abre todas as caixas ao mesmo tempo.
>
>
>
>

**Comment by simas0** [comment]
Os ambientes a serem criados neste momento são:
Para o professor
Resposta 
Definição (não numerada)
Teorema (numeração reinicia em cada página)
Exemplo (numeração reinicia em cada página)
Atividade (numeração reinicia em cada página)

**Comment by gutosurrex** [comment]
Foi feito. Agora assim que você souber a palheta de cores, abra um issue cosmético para mudar as caixas.
