### ISSUE TITLE
Possibilitar itens do tipo a), b), etc.

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#35]

**Comment by gutosurrex** [comment]
Está funcionando. Talvez tenha que apertar Ctrl + Alt + R no navegador para atualizar os arquivos de estilo.

**Comment by simas0** [comment]
Mas no texto para edição fica 1., 2., etc. e no texto em html fica a), b), etc. Melhor ficarem iguais a este segundo, né?

**Comment by gutosurrex** [comment]
Podemos escrever a), b), etc... na edicão também.

Agora já mudei o toolkit de edicão para esse padrão.

**Comment by simas0** [comment]
Mas na barra de ferramentas do ambiente de edição está "1."

Fábio
(21) 99735-8504

2016-10-05 9:29 GMT-03:00 gutosurrex <notifications@github.com>:
