### ISSUE TITLE
Estilos de seta alternativos

### ISSUE THREAD

**Issue by mpfaraujo** [gutosurrex/BookCloud#37]
Eu estava vendo esse [site ](http://tex.stackexchange.com/questions/5461/is-it-possible-to-change-the-size-of-an-arrowhead-in-tikz-pgf) procurando estilos diferentes para as setas (alguns desenhos ficam com setas meio feias ...) talvez seja mais um caso em que basta incluir um pacote no preâmbulo.

**Comment by simas0** [comment]
Ao que me parece com as bibliotecas \usetikzlibrary{arrows} ou \usetikzlibrary{arrows.meta} a coisa já melhoraria bastante. Mas no site indicado pelo @mpfaraujo acima os caras apresentam além destas outras opções não incorporadas às bibliotecas do tikz.

**Comment by gutosurrex** [comment]
Olá,

Já está funcionando.  Basta escrever por exemplo:

```
.. tikz:: Alguns vetores:
   \draw[-latex, thick, red] (0,1) -- (3,5);
   \draw[-latex, thick, red] (2,0) -- (5,4);
   \draw[latex-latex, thick, red] (3,4) -- (6,8);
 ```

Note o `[-latex]` no lugar de `[->]` e `[latex-latex]` no lugar de `[<->]`.
