### ISSUE TITLE
Enumeração com comportamento inesperado após figura em tikz

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#40]
A enumeração só funciona sem os espaços iniciais porque antes dela vem uma figura em tikz. Mas o texto desce uma linha no html. Veja figura:

![screenshot from 2016-10-06 08-45-53](https://cloud.githubusercontent.com/assets/16407253/19151168/a15b3c5c-8ba1-11e6-979a-572131663949.png)

**Comment by gutosurrex** [comment]
Isso não tem a ver com o tikz e sim com as duas linhas que você escreveu depois da lista. Faça assim que funciona:

```
#. Reproduza
#. Nesta situação o deslocamento de cada um dos barcos é sempre o mesmo e pode ser representado pelas componentes

 x de oeste para leste e;
   
 y do sul para o norte.
```
