### ISSUE TITLE
Projeto ensino_medio segue com problemas

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#42]
retangulo_do_simas has requests, mas ao clicar em retangulo_do_simas na lista de ramos recebo a mensagem de erro abaixo.

Talvez seja o caso de se apagar este projeto inteiro.

![screenshot from 2016-10-06 09-05-02](https://cloud.githubusercontent.com/assets/16407253/19151653/39ac1ce0-8ba4-11e6-9a7e-f9952ade9acd.png)

**Comment by gutosurrex** [comment]
Foi deletado!
