### ISSUE TITLE
Seria interessante se ao salvarmos a tela do lado esquerdo mostrasse a página do documento que foi por último alterada.

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#46]
Comentário do Gladson na plataforma. Vou pedir que ele deixe mais claro o que deseja nos comentários abaixo.

**Comment by GladsonAntunes** [comment]
Deixe-me explicar melhor. Quando estamos no ambiente de edição, trabalhando no texto do livro, ao salvarmos o que estamos fazendo aparece do lado direito da tela uma prévia do que foi construído. A cada save o que é exibido do lado direito inicia da primeira página do que já foi desenvolvido. Imagino que quando estejamos mais avançados, com 20, 30 páginas já desenvolvidas, será chato a cada save ter que rolar até a página que foi por último alterada (que serão geralmente as últimas do documento).
Penso que o ideal seria, ao efetuarmos o save, exibir do lado direito o resultado do que acabamos de alterar.

**Comment by gutosurrex** [comment]
Hehe... foi mal mas eu ainda não entendi. Talvez role de fazer um screenshot ou encontrar pra gente ver juntos. Alias, encontrar agora que a galera já está começando a usar a plataforma ia ser bem legal!

**Comment by GladsonAntunes** [comment]
Hahaha...Beleza Augusto! Pessoalmente vai ser mais simples mesmo!



2016-10-13 9:29 GMT-03:00 gutosurrex <notifications@github.com>:

**Comment by simas0** [comment]
Ao que me parece o que está sendo solicitado já está implementado (começou semana passada, eu acho). Seria: ao salvar uma edição, nem a janela de edição nem a janela de visualização se movem. Antes elas voltavam ao início do documento.

Confira, por favor, Gladson. Se não for isso reabra o ISSUE.
