### ISSUE TITLE
Quebrei a plataforma!!

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#49]
Cliquei em salvar após incluir uma figura em tikz, mas eu esqueci de colocar ponto e vírgula no final e ela nunca terminou de salvar. Saí na marra e não conseguia mais editar. Fechei a janela e agora não consigo conectar mais nela.

**Comment by GladsonAntunes** [comment]
Ahhhh..por isso que eu não tô conseguindo acessar! :)

**Comment by gutosurrex** [comment]
Consertado! Ehhh Fábio...

**Comment by simas0** [comment]
Quebrei novamente fazendo a mesma coisa.  :oE

**Comment by simas0** [comment]
A parte boa é que a gente ganha uma folga quando isso acontece...

**Comment by simas0** [comment]
Resolvido ontem à noite.
