### ISSUE TITLE
Como faço para incluir links que abrem em nova aba na plataforma?

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#50]
Por exemplo, o link escrito como a seguir abre na mesma janela e o estudante estará fora do livro...

``Manual do Mundo <https://www.youtube.com/watch?v=Ji7YorM_t_0>`_`

**Comment by gutosurrex** [comment]
Inclua ele normalmente. Agora todos os links externos abrem em uma nova aba.
