### ISSUE TITLE
Pacotes e bibliotecas a serem incluídos no latex da plataforma

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#51]
\usetikzlibrary{intersections} para determinar um ponto como interseção de duas curvas.

**Comment by gutosurrex** [comment]
Está feito. Me passa depois uma lista de todos os pacotes tikz que são importantes.

**Comment by simas0** [comment]
#23 Contém outros pacotes necessários para figuras em tikz, especialmente aqueles usados pelo Geogebra.
