### ISSUE TITLE
commits sem texto ou com texto no ambiente de edição

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#55]
Na imensa maioria dos casos, o texto de até 60 caracteres, que é permitido no momento do commit, não serve para nada. Isso é um bom motivo para realizarmos commits sem texto. Isso tornaria a plataforma mais amigável!

Caso o texto seja imprescindível, eu sugeriria que ele seja muito maior e salvo em etapas, que exista a possibilidade de (mas não a obrigação) se colocar o registro do commit a cada vez que clicar em salvar (sem mudar de tela). Digo isso porque como podemos salvar sem submeter, quase nunca lembramos bem o que foi feito nas edições anteriores do mesmo commit.

**Comment by gutosurrex** [comment]
Cara, eu vou colocar mais espaco pro povo escrever coisas no commit. Mas por agora, eu já fiz uma pequena mudança que eu acho que vai mudar sua impressao das mensagens. Faça um merge agora pra você ver.

**Comment by simas0** [comment]
Agora o texto do commit aparece para o revisor no momento da revisão. Isso já tira ele da inutilidade total!
