### ISSUE TITLE
Ramos eternos que deveriam ser efêmeros

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#61]
> testes_de_figuras, (by @simas) - pdf expires (None) 
> Augusto, (by @augusto) - pdf expires (None) 
> sugestoes_marcos_paulo, (by @mpfaraujo) - pdf expires (None) 

Neste último, não sei se ele fez commit hoje.

**Comment by mpfaraujo** [comment]
Fiz.

**Comment by gutosurrex** [comment]
Um ramo com `expires (None)` não é eterno. Só por algum motivo não está marcado para desaparecer.

Quando um ramo é eterno, não aparece nada (como o Gladson por exemplo).

**Comment by simas0** [comment]
Nada faz o ramo abaixo ganhar prazo de validade. Poderia matá-lo manualmente?
inicio, (by @Luvelasque) - pdf expires (None) 

Por outro lado, o ramo
sugestoes_marcos_paulo, (by @mpfaraujo) - pdf expires (2016-10-26 13:40:05) 
tem sua data de renovação aumentada dia após dia e nunca morre mesmo que não tenha qualquer movimentação (exceto possivelmente visualização). Alguma modificação deve ser feita no código. Se puder matar estes ramos manualmente, seria ótimo!

@gutosurrex

**Comment by gutosurrex** [comment]
Feito

**Comment by simas0** [comment]
Sugestoes_wanderley_2
<https://www.umlivroaberto.com/BookCloud/Volume_1/Sugestoes_wanderley_2/view/index.html>,
(by @wanderley) - pdf
<https://www.umlivroaberto.com/BookCloud/Volume_1/Sugestoes_wanderley_2/pdf>
expires (None)

Fábio
(21) 99735-8504

2016-10-26 10:27 GMT-02:00 gutosurrex <notifications@github.com>:

**Comment by gutosurrex** [comment]
Agora só o dono pode limpar a data de validade ao visitar o ramo. Acho que isso deve resolver o problema dos bots.
