### ISSUE TITLE
Índice do ramo recém criado difere do ancestral 

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#62]
Veja os dois prints abaixo
![screenshot from 2016-10-15 22-50-46](https://cloud.githubusercontent.com/assets/16407253/19414654/e530eec4-9329-11e6-8262-abbd3d204592.png)
![screenshot from 2016-10-15 22-50-32](https://cloud.githubusercontent.com/assets/16407253/19414655/e755f2b2-9329-11e6-9e1a-3dc3c839ec96.png)

**Comment by gutosurrex** [comment]
Veja se foi corrigido depois do seu commit.

**Comment by gutosurrex** [comment]
Acho que está bom agora
