### ISSUE TITLE
Caixa de diálogo avisando que usuário está saindo do ambiente de edição sem salvar 

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#65]
Naturalmente, o ideal é que a caixa apenas apareça, caso alguma alteração tenha sido executada no arquivo. Por exemplo, na DokuWiki, ele não confere se houve edição, mas se a caixa de texto foi selecionada ao menos uma vez (foi clicada).

**Comment by gutosurrex** [comment]
Feito!
