### ISSUE TITLE
Tamanho de figuras não está funcionando

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#74]
Veja o final da seção abaixo:

https://www.umlivroaberto.com/BookCloud/Volume_1/ramo_simas/edit/geometria

As figuras estão muito pequenas e não conseguimos aumentá-la.

**Comment by gutosurrex** [comment]
Tem uma linha em branco entre `.. figure` e os parâmetros. O correto seria:

```
   .. figure:: https://www.umlivroaberto.com/livro/lib/exe/fetch.php?w=90&h=45&t=1477748921&tok=2ab94d&media=bloco_mesa_1.jpg
      :align: center
      :width: 400px
```
