### ISSUE TITLE
Estrutura de seções não funciona de modo apropriado

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#79]
1. Capítulo devia estar num nível acima de subseção. 
Acho que este problema 1 surgiu porque no início do arquivo eu havia substituído 
```
**************
Vetores no plano
**************
```
por 
```
#########
Vetores no plano
#########
```
a fim de tentar resolver o issue #78. Primeiro print foi obtido com `##` acima e segundo print com `**` no início do arquivo.
 
2. Seção deveria ser um dos níveis permitidos... simplesmente não aparece na visualização.

![screenshot from 2016-11-09 05-39-07](https://cloud.githubusercontent.com/assets/16407253/20130598/fbeb1a5e-a63e-11e6-8d23-151273ccaa72.png)

![screenshot from 2016-11-09 06-00-08](https://cloud.githubusercontent.com/assets/16407253/20131104/809b2160-a642-11e6-9f82-803c64bb6562.png)

relaciona-se com #78 Numeração na tabela de conteúdos.

**Comment by gutosurrex** [comment]
Cara, cada seção está com um estilo diferente. Eu vi:

```
*************
Vetores no plano
*************
```

```
=======
Funções
=======
```

```
Probabilidade e Estatística
******************
```

Isso confunde o Sphinx e deve ser tranferido para o Issues do livro, não da plataforma.

**Comment by simas0** [comment]
Você está dizendo que se usarmos o mesmo padrão de enumeração em todo o projeto as seções vai funcionar? Senão precisaremos colocar o Sphinx numa terapia para ele se entender...
