### ISSUE TITLE
A enumeração no Sphinx é sempre manual?!

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#80]
Quando temos uma enumeração do tipo
  ```
 1. primeira parte da atividade
   2. outra parte 
   3. parte diferente da atividade
```
e decidimos reposicionar o itens, por exemplo,
```
   1. primeira parte da atividade
   3. parte diferente da atividade
   2. outra parte 
```
a enumeração estraga... Isso retira uma das principais vantagens da enumeração automática para o elaborador e encoraja a enumeração manual.

**Comment by gutosurrex** [comment]
Podemos usar

```
#. primeira parte
#. segunda parte
#. terceira parte
```

E ele numera automaticamente.
