### ISSUE TITLE
Internal serve error

### ISSUE THREAD

**Issue by simas0** [gutosurrex/BookCloud#9]
Ao entrar em _ensino-medio --> retangulo_do_simas_ surge "Merge requests Request from corigir-tikz". 
Ao clicar em "corrigir-tikz" surge a mensagem de erro "Internal serve error".

**Comment by simas0** [comment]
Especialmente problemático porque me impede de acessar meu ramo do trabalho.

**Comment by gutosurrex** [comment]
Veja se está funcionando agora...

**Comment by simas0** [comment]
Funciona! :+1:
Obrigado!
